# -*- coding: utf-8 -*-
"""ChessPreprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11oR0oIsv_15amTWCh3lxEXduobWZQp3g
"""

#The two lines below are colab specific. I will include the file

from google.colab import files
uploaded = files.upload()

myfile = open("lichess_tournament_2022.12.03_EcJR7jAC_hourly-bullet.txt", "rt") # open lorem.txt for reading text
contents = myfile.read()         # read the entire file to string
myfile.close()                   # close the file
#print(contents)                  # print string contents

mylines = []                             # Declare an empty list named mylines.
with open ('lichess_tournament_2022.12.03_EcJR7jAC_hourly-bullet.txt', 'rt') as myfile: # Open lichess_pgn_(etc).txt for reading text data.
    for myline in myfile:                # For each line, stored as myline,
        mylines.append(myline)           # add its contents to mylines.
print(mylines)                           # Print the list.

i = 0

#935 games played in total in this chess tournament

#When using full dataset instead of one game, will have to change 17+20*i

#Rows for data are 17, 37, 57, etc. 

#Row of moves for the first game
print(mylines[17+20*i])

z = 1

#Place each pair of moves into tuples, such that: [(e4, g6), (d4, Bg7), etc.] While loop to do this for each match.

for x in mylines[17*i]:

print(mylines[37])

